name: dart_file_organizer
description: A command-line tool to organize files based on their type.
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  sqlite3: ^2.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  dart_file_orginizer: bin/dart_file_organizer.dart
